#!/usr/bin/env python

"""Getdata.py: Imports LargeCap, MidCap, SmallCap, Index and Commodities tags for the Swedish Stock market."""

__author__      = "John Nilsson"
__copyright__   = "Copyright 2016, Project Stock Trade"

# Large Cap Stocks
def load_stock_list(tag):
    if tag == 'LargeCap':
        stdict = {'AAK':                    ['510834',    'AAK.ST'],
            'ABB Ltd':                      ['77151',     'ABB.ST'],
            'Africa Oil':                   ['2617823',   'AOI.ST'],
            'Alfa Laval':                   ['69090',     'ALFA.ST'],
            'Assa Abloy':                   ['69111',     'ASSA-B.ST'],
            'AstraZeneca':                  ['68978',     'AZN.ST'],
            'Altas Copco A':                ['69332',     'ATCO-A.ST'],
            'Altas Copco B':                ['69331',     'ATCO-B.ST'],
            'Atrium Ljungberg B':           ['69114',     'LJGR-B.ST'],
            'Autoliv SDB':                  ['69084',     'ALIV-SDB.ST'],
            'Axfood':                       ['180001',    'AXFO.ST'],
            'Axis':                         ['187255',    'AXIS.ST'],
            'Betsson B':                    ['579815',    'BETS-B.ST'],
            'Billerud Korsnaes':            ['304054',    'BILL.ST'],
            'Boliden':                      ['68969',     'BOL.ST'],
            'Castellum':                    ['69078',     'CAST.ST'],
            'Com Hem Holding':              ['21140780',  'COMH.ST'],
            'Electrolux A':                 ['69325',     'ELUX-A.ST'],
            'Electrolux B':                 ['69324',     'ELUX-B.ST'],
            'Elekta B':                     ['69131',     'EKTA-B.ST'],
            'EnQuest PLC':                  ['2273674',   'ENQ.ST'],
            'Ericsson A':                   ['293523',    'ERIC-A.ST'],
            'Ericsson B':                   ['293520',    'ERIC-B.ST' ],
            'Fabege':                       ['496000',    'FABG.ST'],
            'Fast. Balder B':               ['508524',    'BALD-B.ST'],
            'Getinge B':                    ['328395',    'GETI-B.ST'],
            'Handelsbanken A':              ['69251',     'SHB-A.ST'],
            'Handelsbanken B':              ['69247',     'SHB-B.ST'],
            'Hennes & Mauritz B':           ['69316',     'HM-B.ST' ],
            'Hexagon B':                    ['69288',     'HEXA-B.ST'],
            'Hexpol B':                     ['1196446',   'HPOL-B.ST'],
            'Holmen A':                     ['207662',    'HOLM-A.ST'],
            'Holmen B':                     ['206417',    'HOLM-B.ST'],
            'Huvudstaden A':                ['69315',     'HUFV-A.ST'],
            'Huvudstaden C':                ['69314',     'HUFV-C.ST'],
            'Husqvarna A':                  ['576531',    'HUSQ-A.ST'],
            'Husqvarna B':                  ['576532',    'HUSQ-B.ST'],
            'ICA Gruppen':                  ['15307864',  'ICA.ST'],
            'Industrivaerlden A':           ['69282',     'INDU-A.ST'],
            'Industrivaerlden C':           ['69281',     'INDU-C.ST'],
            'Indutrade':                    ['511324',    'INDT.ST'],
            'Intrum Justitia':              ['335770',    'IJ.ST'],
            'Investor A':                   ['69278',     'INVE-A.ST'],
            'Investor B':                   ['69277',     'INVE-B.ST'],
            'JM':                           ['277512',    'JM.ST'],
            'Kinnevik A':                   ['69318',     'KINV-A.ST'],
            'Kinnevik B':                   ['69319',     'KINV-B.ST'],
            'Latour B':                     ['69283',     'LATO-B.ST'],
            'Lifco B':                      ['23656485',  'LIFCO-B.ST'],
            'Loomis B':                     ['1829538',   'LOOM-B.ST'],
            'Lundbergforetagen B':          ['69240',     'LUND-B.ST'],
            'Lundin Mining Corp. SDB':      ['481350',    'LUMI-SDB.ST'],
            'Lundin Petroleum':             ['293288',    'LUPE.ST'],
            'Meda A':                       ['69099',     'MEDA-A.ST'],
            'Melker Schorling':             ['585865',    'MELK.ST'],
            'Millicom Int. Cellular SDB':   ['494060',    'MIC-SDB.ST'],
            'Modern Times Group A':         ['206484',    'MTG-A.ST'],
            'Modern Times Group B':         ['203514',     'MTG-B.ST'],
            'NCC A':                        ['69267',     'NCC-A.ST'],
            'NCC B':                        ['69266',     'NCC-B.ST'],
            'NIBE Industrier B':            ['69071',     'NIBE-B.ST'],
            'Nobia':                        ['336452',    'NOBI.ST'],
            'Nordea Bank':                  ['506886',    'NDA-SEK.ST'],
            'Oriflame Holding':             ['494059',    'ORI.ST'],
            'Pandox B':                     ['27208886',  'PNDX-B.ST'],
            'Peab B':                       ['69194',     'PEAB-B.ST'],
            'Rato A':                       ['69275',     'RATO-A.ST'],
            'Ratos pref':                   ['15735617',  'RATO-PREF.ST'],
            'Saab B':                       ['69018',     'SAAB-B.ST'],
            'Sandvik':                      ['175284',    'SAND.ST'],
            'SCA A':                        ['69330',     'SCA-A.ST'],
            'SCA B':                        ['69329',     'SCA-B.ST'],
            'SEB A':                        ['69253',     'SEB-A.ST'],
            'SEB C':                        ['69252',     'SEB-C.ST'],
            'Securitas B':                  ['69144',     'SECU-B.ST'],
            'Skanska B':                    ['69326',     'SKA-B.ST'],
            'SKF A':                        ['69305',     'SKF-A.ST'],
            'SKF B':                        ['69304',     'SKF-B.ST'],
            'SSAB A':                       ['69163',     'SSAB-A.ST'],
            'SSAB B':                       ['69162',     'SSAB-B.ST'],
            'Stora Enso A':                 ['68992',     'STE-A.ST'],
            'Stora Enso R':                 ['68991',     'STE-R.ST'],
            'Swedbank A':                   ['586553',    'SWED-A.ST'],
            'Swedish Match':                ['70073',     'SWMA.ST'],
            'Swedish Orphan Biovitrum':     ['2383439',   'SOBI.ST'],
            'Tele2 A':                      ['254383',    'TEL2-A.ST'],
            'Tele2 B':                      ['254384',    'TEL2-B.ST'],
            'TeliaSonera':                  ['358575',    'TLSN.ST'],
            'Tieto Oyj':                    ['78816',     'TIEN.ST'],
            'Trelleborg B':                 ['69303',     'TREL-B.ST'],
            'Volvo A':                      ['69302',     'VOLV-A.ST'],
            'Volvo B':                      ['69301',     'VOLV-B.ST'],
            'Wallenstam B':                 ['69218',     'WALL-B.ST']}

    # Mid Cap Stocks
    elif tag == 'MidCap':
        stdict = {'ACTI.ST': ['432115',    'Active Biotech'],
            'ADDT-B.ST':     ['292912',    'Addtech B'],
            'ALIG.ST':       ['27183617',  'Alimak Group'],
            'ARCM.ST':       ['10409669',  'Arcam'],
            'AZA.ST':        ['298618',    'Avanza Bank Holding'],
            'BBTO-B.ST':     ['622577',    'B&B TOOLS B'],
            'BACTI-B.ST':    ['21182778',  'Bactiguard Holding'],
            'BEIA-B.ST':     ['69183',     'Beijer Alma B'],
            'BEIJ-B.ST':     ['69234',     'Beijer Ref B'],
            'BILI-A.ST':     ['69225',     'Bilia A'],
            'BIOG-B.ST':     ['69015',     'BioGaia B'],
            'PXXS-SDB.ST':   ['2084628',   'BlackPearl Resources SDB'],
            'BUFAB.ST':      ['19218844',  'Bufab Holding'],
            'BURE.ST':       ['69207',     'Bure Equity'],
            'BMAX.ST':       ['2334993',   'Byggmax Group'],
            'CAPIO.ST':      ['27400181',  'Capio'],
            'CATE.ST':       ['571263',    'Catena'],
            'CCC.ST':        ['5482154',   'Cavotec'],
            'CLAS-B.ST':     ['206677',    'Clas Ohlson B'],
            'CLA-B.ST':      ['1827384',   'Cloetta B'],
            'COLL.ST':       ['27064472',  'Collector'],
            'COIC.ST':       ['3748674',   'Concentric'],
            'COOR.ST':       ['27160815',  'Coor Service MGT'],
            'CORE.ST':       ['151369',    'Corem Property Group'],
            'CORE-PREF.ST':  ['2261394',   'Corem Property Group Pref'],
            'CRED-A.ST':     ['7568365',   'Creades A'],
            'DCAR-B.ST':     ['19934001',  'D. Carnegie & Co B'],
            'DIOS.ST':       ['69186',     'Dios Fastigheter'],
            'DUNI.ST':       ['684182',    'Duni'],
            'DUST.ST':       ['25041449',  'Dustin Group'],
            'ECEX.ST':       ['675500',    'East Capital Explorer'],
            'ELTEL.ST':      ['24937847',  'Eltel'],
            'ENRO.ST':       ['234453',    'Eniro'],
            'ENRO-PREF.ST':  ['10771807',  'Eniro pref'],
            'FAG.ST':        ['69083',     'Fagerhult'],
            'FPAR.ST':       ['69133',     'Fast Partner'],
            'FPAR-PREF.ST':  ['15586242',  'Fast Partner Pref'],
            'FOI-B.ST':      ['21293796',  'Fenix Outdoor Int.'],
            'FING-B.ST':     ['205786',    'Fingerprint Cards B'],
            'GRNG.ST':       ['22957004',  'Graenges'],
            'GUNN.ST':       ['69136',     'Gunnebo'],
            'HLDX.ST':       ['69317',     'Haldex'],
            'HEBA-B.ST':     ['69119',     'HEBA B'],
            'HEMF.ST':       ['19635831',  'Hemfosa Fastigheter'],
            'HEMF-PREF.ST':  ['23998703',  'Hemfosa Fastigheter Pref'],
            'HIQ.ST':        ['68976',     'HiQ International'],
            'HMS.ST':        ['667147',    'HMS Networks'],
            'HOFI.ST':       ['25799360',  'Hoist Finance'],
            'IFS-B.ST':      ['69058',     'Industrial & Financial Sys. B'],
            'INWI.ST':       ['22753281',  'Inwido'],
            'ITAB-B.ST':     ['69167',     'ITAB Shop Concept B'],
            'KAHL.ST':       ['554634',    'KappAhl'],
            'KLOV-A.ST':     ['337578',    'Klovern A'],
            'KLOV-B.ST':     ['338455',    'Klovern B'],
            'KLOV-PREF.ST':  ['7061996',   'Klovern PREF'],
            'KLED.ST':       ['68974',     'Kungsleden'],
            'LAGR-B.ST':     ['292920',    'Lagercrantz Group B'],
            'LIAB.ST':       ['601182',    'Lindab International'],
            'LUC.ST':        ['847252',    'Lucara Diamond Corp'],
            'LUG.ST':        ['24172123',  'Lundin Gold'],
            'MVIR-B.ST':     ['70078',     'Medivir B'],
            'MEKO.ST':       ['637525',    'Mekonomen'],
            'MUNK1S.ST':     ['23913170',  'Munksjo Oyj'],
            'MYCR.ST':       ['20820044',  'Mycronic'],
            'NMAN.ST':       ['627574',    'Nederman Holding'],
            'NET-B.ST':      ['1871693',   'NetEnt B'],
            'NEWA-B.ST':     ['69036',     'New Wave B'],
            'NGQ.ST':        ['21182777',  'NGEx Resources'],
            'NOBINA.ST':     ['27208887',  'Nobina'],
            'NOLA-B.ST':     ['69224',     'Nolato B'],
            'NDX.ST':        ['27183620',  'Nordax Group'],
            'NN-B.ST':       ['296374',    'Nordnet B'],
            'NP3.ST':        ['23854041',  'NP3 Fastigheter'],
            'OASM.ST':       ['2383442',   'Oasmia Pharmaceutical'],
            'OEM-B.ST':      ['69233',     'OEM International B'],
            'OPUS.ST':       ['570052',    'Opus Group'],
            'ORX.ST':        ['513986',    'Orexo'],
            'PLAZ-B.ST':     ['18003985',  'Platzer Fastigheter'],
            'PROE-B.ST':     ['206346',    'Proffice B'],
            'QLRO.ST':       ['24447987',  'Qliro Group'],
            'RECI-B.ST':     ['19846466',  'Recipharm'],
            'REZT.ST':       ['600482',    'Rezidor Hotel Group'],
            'SAGA-A.ST':     ['10091008',  'Sagax A'],
            'SAGA-B.ST':     ['14640841',   'Sagax B'],
            'SAGA-PREF.ST':  ['550761',    'Sagax Pref'],
            'SAS.ST':        ['69271',     'SAS'],
            'SAS-PREF.ST':   ['19423547',  'SAS Pref'],
            'SCST.ST':       ['21309295',  'Scandi Standard'],
            'SECT-B.ST':     ['203610',    'SECTRA B'],
            'SMF.ST':        ['5491151',   'Semafo'],
            'SKIS-B.ST':     ['298619',    'SkiStar B'],
            'SWEC-A.ST':     ['68997',     'SWECO A'],
            'SWEC-B.ST':     ['68996',     'SWECO B'],
            'SWOL-B.ST':     ['576278',    'Swedol B'],
            'SYSR.ST':       ['664926',    'Systemair'],
            'TETY.ST':       ['448961',    'Tethys Oil'],
            'THULE.ST':      ['23731618',  'Thule Group'],
            'TWW.ST':        ['515539',    'Transcom WorldWide'],
            'TRMO.ST':       ['3646033',   'Transmode'],
            'TRI.ST':        ['15245116',  'Tribona'],
            'TROAX.ST':      ['25843829',  'Troax Group'],
            'UNIB-SDB.ST':   ['494061',    'Unibet Group'],
            'VBG-B.ST':      ['69179',     'VBG GROUP B'],
            'VICP-A.ST':     ['20457109',  'Victoria Park A'],
            'VICP-B.ST':     ['20536432',  'Victoria Park B'],
            'VICP-Pref.ST':  ['16130800',  'Victoria Park Pref'],
            'VITR.ST':       ['283902',    'Vitrolife'],
            'WIHL.ST':       ['335811',    'Wihlborgs Fastigheter'],
            'AF-B.ST':       ['1154486',   'AF B'],
            'ORES.ST':       ['69273',     'Oresund']}

    # Small Cap Stocks
    elif tag == 'SmallCap':
        stdict = {'ACAN-B.ST':   ['574378',    'Acando AB B'],
            'ANOD-B.ST':         ['440578',    'Addnode Group AB'],
            'ALNX.ST':           ['3776355',   'Allenex AB'],
            'ATEL-A.ST':         ['14706520',  'AllTele Allmaenna Svenska Telef'],
            'ANOT.ST':           ['334827',    'Anoto Group AB'],
            'ARP.ST':            ['13226398',  'Arctic Paper S.A'],
            'ARISE.ST':          ['15504467',  'Arise AB'],
            'AVEG-B.ST':         ['669857',    'Avega Group AB B'],
            'BEGR.ST':           ['599660',    'BE Group AB'],
            'BELE.ST':           ['182384',    'Beijer Electronics AB'],
            'BRG-B.ST':          ['69217',     'Bergs Timber AB B'],
            'BESQ.ST':           ['21048516',  'Besqab AB'],
            'BINV.ST':           ['279827',    'BioInvent International AB'],
            'BIOT.ST':           ['621544',    'Biotage AB'],
            'BORG.ST':           ['626265',    'Bjorn Borg AB'],
            'BEF-SDB.ST':        ['2068699',   'Black Earth Farming Ltd SDB'],
            'BONG.ST':           ['69175',     'Bong AB'],
            'BOUL.ST':           ['3797717',   'Boule Diagnostics AB'],
            'BTS-B.ST':          ['279096',    'BTS Group AB B'],
            'BULTEN.ST':         ['22310359',  'Bulten AB'],
            'CEVI.ST':           ['629473',    'CellaVision AB'],
            'CCOR-B.ST':         ['69227',     'Concordia Maritime AB B'],
            'CONS-B.ST':         ['69126',     'Consilium AB B'],
            'CRAD-B.ST':         ['636235',    'C-Rad AB B'],
            'CTT.ST':            ['69042',     'CTT Systems AB'],
            'CYBE.ST':           ['203335',    'Cybercom Group AB'],
            'DEDI.ST':           ['3527074',   'Dedicare AB B'],
            'DGC.ST':            ['1248669',   'DGC One AB'],
            'DORO.ST':           ['69139',     'Doro AB'],
            'DURC-B.ST':         ['206780',    'Duroc AB B'],
            'ELAN-B.ST':         ['69166',     'Elanders AB B'],
            'ELEC.ST':           ['571689',    'Electra Gruppen AB'],
            'ELOS-B.ST':         ['1161370',   'Elos AB B'],
            'ENDO.ST':           ['632042',    'Endomines AB'],
            'ENEA.ST':           ['69151',     'Enea AB'],
            'EOLU-B.ST':         ['2060122',   'Eolus Vind AB B'],
            'EPIS-B.ST':         ['2726339',   'Episurf Medical AB B'],
            'ETX.ST':            ['2726340',   'Etrion Corporation'],
            'EWRK.ST':           ['1170350',   'eWork Scandinavia AB'],
            'FEEL.ST':           ['181786',    'Feelgood Svenska AB'],
            'FPIP.ST':           ['457830',    'FormPipe Software AB'],
            'G5EN.ST':           ['1799949',   'G5 Entertainment AB'],
            'GHP.ST':            ['1747277',   'Global Health Partner AB'],
            'HAV-B.ST':          ['69169',     'Havsfrun Investment AB B'],
            'IAR-B.ST':          ['3638120',   'I.A.R Systems Group AB B'],
            'IS.ST':             ['3748672',   'Image Systems AB'],
            'ICTA-B.ST':         ['236272',    'Intellecta AB B'],
            'IVSO.ST':           ['1243048',   'Invisio Communications AB'],
            'KABE-B.ST':         ['69228',     'Kabe AB B'],
            'KARO.ST':           ['75160',     'Karo Bio AB'],
            'KDEV.ST':           ['3457653',   'Karolinska Development AB'],
            'KNOW.ST':           ['69043',     'KnowIT AB'],
            'LAMM-B.ST':         ['1255826',   'Lammhults Design Group AB'],
            'MEAB-B.ST':         ['206781',    'Malmbergs Elektriska AB B'],
            'MSAB-B.ST':         ['6769024',   'Micro Systemation AB B'],
            'MSON-A.ST':         ['609580',    'Midsona AB ser A'],
            'MIDW-A.ST':         ['69154',     'Midway Holding AB A'],
            'MIDW-B.ST':         ['609581',    'Midway Holding AB B'],
            'MOB.ST':            ['620126',    'Moberg Pharma AB'],
            'MQ.ST':             ['2374348',   'MQ Holding AB'],
            'MSC-B.ST':          ['69019',     'MSC Konsult AB B'],
            'MULQ.ST':           ['116160',    'MultiQ International AB'],
            'NAXS.ST':           ['627311',    'Naxs Nordic Access Buyout Fund'],
            'NMAN.ST':           ['627574',    'Nederman Holding AB'],
            'NETI-B.ST':         ['204876',    'Net Insight AB B'],
            'NVP.ST':            ['1747278',   'NeuroVive Pharmaceutical AB'],
            'NOMI.ST':           ['604537',    'Nordic Mines AB'],
            'NSP-B.ST':          ['571515',    'Nordic Service Partners Holdin'],
            'NOTE.ST':           ['460953',    'Note AB'],
            'NOVE.ST':           ['170743',    'Novestra AB'],
            'NTEK-B.ST':         ['203377',    'Novotek AB B'],
            'ODD.ST':            ['631946',    'Odd Molly International AB'],
            'OPCO.ST':           ['68987',     'Opcon AB'],
            'ORTI-A.ST':         ['69098',     'Ortivus AB A'],
            'ORTI-B.ST':         ['69097',     'Ortivus AB B'],
            'OP.ST':             ['19142632',  'Oscar Properties Holding AB'],
            'OP-PREF.ST':        ['15586241',  'Oscar Properties Holding AB PR'],
            'PAR.ST':            ['577798',    'PA Resources AB'],
            'POOL-B.ST':         ['206673',    'Poolia AB B'],
            'PREC.ST':           ['587465',    'Precise Biometrics AB'],
            'PREV-B.ST':         ['69013',     'Prevas AB B'],
            'PRIC-B.ST':         ['69106',     'Pricer AB B'],
            'PACT.ST':           ['78048',     'Proact IT Group AB'],
            'PROB.ST':           ['480759',    'Probi AB'],
            'PROF-B.ST':         ['69066',     'ProfilGruppen AB B'],
            'RAY-B.ST':          ['395359',    'RaySearch Laboratories AB'],
            'REJL-B.ST':         ['604648',    'Rejlers AB'],
            'RNBS.ST':           ['283901',    'RNB Retail AND Brands AB'],
            'RROS.ST':           ['69178',     'Rottneros AB'],
            'SEAM.ST':           ['10319041',  'Seamless Distribution AB'],
            'SEMC.ST':           ['69077',     'Semcon AB'],
            'SENS.ST':           ['250197',    'Sensys Traffic AB'],
            'SHEL-B.ST':         ['12777646',  'Shelton Petroleum AB B'],
            'SINT.ST':           ['335915',    'SinterCast AB'],
            'SOF-B.ST':          ['204095',    'Softronic AB B'],
            'SPOR.ST':           ['12470165',  'Sportamore AB'],
            'STWK.ST':           ['18092997',  'Stockwik Forvaltning AB'],
            'SVIK.ST':           ['273853',    'Studsvik AB'],
            'SVED-B.ST':         ['69052',     'Svedbergs i Dalstorp AB B'],
            'SVOL-A.ST':         ['69209',     'Svolder AB A'],
            'SVOL-B.ST':         ['69208',     'Svolder AB B'],
            'TRAC-B.ST':         ['206766',    'Traction AB B'],
            'TRAD.ST':           ['513737',    'TradeDoubler AB'],
            'UFLX-B.ST':         ['480001',    'Uniflex AB B'],
            'VRG-B.ST':          ['1932431',   'Venue Retail Group AB'],
            'VSSAB-B.ST':        ['26295673',  'VIKING SUPPLY SHIPS'],
            'VIT-B.ST':          ['208182',    'Vitec Software Group AB B'],
            'XANO-B.ST':         ['498101',    'Xano Industri AB B']}

    # Index
    elif tag == 'Index':
        stdict = {'^OMX':        ['479776',   'OMX30'],
            'DAX':               ['7165256',  'S&P500'],
            '^GSPC':             ['5514295',  'DAX30']}

    # Commodities
    elif tag == 'Commodities':
        stdict = {'GOLD':        ['2327121',   'Gold'],
            'BNO':              ['2327059',   'Brent Oil'],
            'WTI':              ['2327086',   'WTI Oil']}

    return stdict




